### ISSUE TITLE
JsonMarshlor has no check for fields type of Date.

### ISSUE THREAD

**Issue by JalalHussain** [sdcote/dataframe#6]
The JSONMarshaler has no check for the DataFields who's type is Date, as result it calls the tooString method of the date which totally changes the date format in the resultant String.
There needs to be check for date(15), the fields getStringValue() method should be called.

**Comment by JalalHussain** [comment]
#Issue

**Comment by sdcote** [comment]
I have posted a unit test and fix for what I believe to be the problem. The JSON Marshaler now uses the same ISO date format when marshaling date fields to JSON as the DateField uses to generate its string values. Commit 313c45fafdcfd20db1b0db910dddf02fea3985de resulting in version 1.0.6.

**Comment by JalalHussain** [comment]
Exactly this was needed to be done, the dependency reference of the version update of the DataFrame in Coyote should also be updated.
